In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp
import scipy.stats as ss
from collections import OrderedDict
from IPython.display import display

En primer lugar vamos a plantear nuestra hipótesis
* **H0** = "las dos variables en estudio son independientes"
* **H1** = "las dos variables en estudio están relacionadas"

Como en los juicios, en estadística, las variables son independientes hasta que demostremos lo contrario.

In [2]:
d = OrderedDict()
d['Peor'] = [7, 15, 10, 5]
d['Igual'] = [28, 20, 30, 40]
d['Mejor'] = [115, 85, 90, 115]

df = pd.DataFrame(data=d)
df = df.rename({0: 'Tratamiento1', 1: 'Tratamiento2', 2: 'Tratamiento3', 3: 'Tratamiento4'})
df

Peor  Igual  Mejor
Tratamiento1     7     28    115
Tratamiento2    15     20     85
Tratamiento3    10     30     90
Tratamiento4     5     40    115

In [3]:
#https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.contingency.expected_freq.html#scipy.stats.contingency.expected_freq
ndarray_fe = ss.contingency.expected_freq(df)
ndarray_fe

array([[  9.91071429,  31.60714286, 108.48214286],
       [  7.92857143,  25.28571429,  86.78571429],
       [  8.58928571,  27.39285714,  94.01785714],
       [ 10.57142857,  33.71428571, 115.71428571]])

In [4]:
#https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.chi2_contingency.html
#chi2(float) : The test statistic.
#p(float) : The p-value of the test
#dof(int) : Degrees of freedom
#expected(ndarray, same shape as observed) : The expected frequencies, based on the marginal sums of the table.

chi2, p, dof, ex = ss.chi2_contingency(df.values, correction=False)
print("Chi2 =", chi2)
print("P-value =", p)
print("DoF =", dof)
print("Exp =", ex)

Chi2 = 13.870898712706621
P-value = 0.031112017842916905
DoF = 6
Exp = [[  9.91071429  31.60714286 108.48214286]
 [  7.92857143  25.28571429  86.78571429]
 [  8.58928571  27.39285714  94.01785714]
 [ 10.57142857  33.71428571 115.71428571]]


In [5]:
def calc_conf(confianza):
    return (100 - confianza) / 100

# Queremos confianza al 95%
if p < calc_conf(95):
    print("Rechazo H0 ==> Las Variables Estan Correlacionadas")
else:
    print("Acepto H0 ==> Las Variables Son Independientes")

Rechazo H0 ==> Las Variables Estan Correlacionadas


In [ ]:
#https://www.uoc.edu/in3/emath/docs/Chi_cuadrado.pdf